site_name: iDEC 2022 | USTC

theme:
  name: material
  logo: img/idec-wiki-logo-white-bg.png
  favicon: img/idec-wiki-logo.png

  palette:
    primary: light blue
    accent: blue

  features:
    - navigation.sections

markdown_extensions:
  - footnotes

  # For MathJax
  - pymdownx.arithmatex:
      generic: true

  # For buttons and image control
  - attr_list

extra_javascript:
  
edit_uri: blob/main/

repo_url: https://github.com/idec-teams/2022_USTC

copyright: Copyright &copy; 2022 iDEC. CC-BY-4.0 | The International Directed Evolution Competition (iDEC) is a Scottish Charitable Incorporate Organisation (SCIO), registered in Scotland, with charity number：SC050826

